lib/pleroma/web/router.ex
# Pleroma: A lightweight social networking server
# Copyright © 2017-2022 Pleroma Authors <https://pleroma.social/>
# SPDX-License-Identifier: AGPL-3.0-only

defmodule Pleroma.Web.Router do
  use Pleroma.Web, :router
  import Phoenix.LiveDashboard.Router

  pipeline :accepts_html do
    plug(:accepts, ["html"])
  end

  pipeline :accepts_html_xml do
    plug(:accepts, ["html", "xml", "rss", "atom"])
  end

  pipeline :accepts_html_json do
    plug(:accepts, ["html", "activity+json", "json"])
  end

  pipeline :accepts_html_xml_json do
    plug(:accepts, ["html", "xml", "rss", "atom", "activity+json", "json"])
  end

  pipeline :accepts_xml_rss_atom do
    plug(:accepts, ["xml", "rss", "atom"])
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
  end

  pipeline :oauth do
    plug(:fetch_session)
    plug(Pleroma.Web.Plugs.OAuthPlug)
    plug(Pleroma.Web.Plugs.UserEnabledPlug)
    plug(Pleroma.Web.Plugs.EnsureUserTokenAssignsPlug)
  end

  # Note: expects _user_ authentication (user-unbound app-bound tokens don't qualify)
  pipeline :expect_user_authentication do
    plug(Pleroma.Web.Plugs.ExpectAuthenticatedCheckPlug)
  end

  # Note: expects public instance or _user_ authentication (user-unbound tokens don't qualify)
  pipeline :expect_public_instance_or_user_authentication do
    plug(Pleroma.Web.Plugs.ExpectPublicOrAuthenticatedCheckPlug)
  end

  pipeline :authenticate do
    plug(Pleroma.Web.Plugs.OAuthPlug)
    plug(Pleroma.Web.Plugs.BasicAuthDecoderPlug)
    plug(Pleroma.Web.Plugs.UserFetcherPlug)
    plug(Pleroma.Web.Plugs.AuthenticationPlug)
  end

  pipeline :after_auth do
    plug(Pleroma.Web.Plugs.UserEnabledPlug)
    plug(Pleroma.Web.Plugs.SetUserSessionIdPlug)
    plug(Pleroma.Web.Plugs.EnsureUserTokenAssignsPlug)
    plug(Pleroma.Web.Plugs.UserTrackingPlug)
  end

  pipeline :base_api do
    plug(:accepts, ["json"])
    plug(:fetch_session)
    plug(:authenticate)
    plug(OpenApiSpex.Plug.PutApiSpec, module: Pleroma.Web.ApiSpec)
  end

  pipeline :no_auth_or_privacy_expectations_api do
    plug(:base_api)
    plug(:after_auth)
    plug(Pleroma.Web.Plugs.IdempotencyPlug)
  end

  # Pipeline for app-related endpoints (no user auth checks — app-bound tokens must be supported)
  pipeline :app_api do
    plug(:no_auth_or_privacy_expectations_api)
  end

  pipeline :api do
    plug(:expect_public_instance_or_user_authentication)
    plug(:no_auth_or_privacy_expectations_api)
  end

  pipeline :authenticated_api do
    plug(:expect_user_authentication)
    plug(:no_auth_or_privacy_expectations_api)
    plug(Pleroma.Web.Plugs.EnsureAuthenticatedPlug)
  end

  pipeline :admin_api do
    plug(:expect_user_authentication)
    plug(:base_api)
    plug(Pleroma.Web.Plugs.AdminSecretAuthenticationPlug)
    plug(:after_auth)
    plug(Pleroma.Web.Plugs.EnsureAuthenticatedPlug)
    plug(Pleroma.Web.Plugs.UserIsStaffPlug)
    plug(Pleroma.Web.Plugs.IdempotencyPlug)
  end

  pipeline :require_admin do
    plug(Pleroma.Web.Plugs.UserIsAdminPlug)
  end

  pipeline :require_privileged_role_users_delete do
    plug(:admin_api)
    plug(Pleroma.Web.Plugs.EnsurePrivilegedPlug, :users_delete)
  end

  pipeline :require_privileged_role_users_manage_credentials do
    plug(:admin_api)
    plug(Pleroma.Web.Plugs.EnsurePrivilegedPlug, :users_manage_credentials)
  end

  pipeline :require_privileged_role_messages_read do
    plug(:admin_api)
    plug(Pleroma.Web.Plugs.EnsurePrivilegedPlug, :messages_read)
  end

  pipeline :require_privileged_role_users_manage_tags do
    plug(:admin_api)
    plug(Pleroma.Web.Plugs.EnsurePrivilegedPlug, :users_manage_tags)
  end

  pipeline :require_privileged_role_users_manage_activation_state do
    plug(:admin_api)
    plug(Pleroma.Web.Plugs.EnsurePrivilegedPlug, :users_manage_activation_state)
  end

  pipeline :require_privileged_role_users_manage_invites do
    plug(:admin_api)
    plug(Pleroma.Web.Plugs.EnsurePrivilegedPlug, :users_manage_invites)
  end

  pipeline :require_privileged_role_reports_manage_reports do
    plug(:admin_api)
    plug(Pleroma.Web.Plugs.EnsurePrivilegedPlug, :reports_manage_reports)
  end

  pipeline :require_privileged_role_users_read do
    plug(:admin_api)
    plug(Pleroma.Web.Plugs.EnsurePrivilegedPlug, :users_read)
  end

  pipeline :require_privileged_role_messages_delete do
    plug(:admin_api)
    plug(Pleroma.Web.Plugs.EnsurePrivilegedPlug, :messages_delete)
  end

  pipeline :require_privileged_role_emoji_manage_emoji do
    plug(:admin_api)
    plug(Pleroma.Web.Plugs.EnsurePrivilegedPlug, :emoji_manage_emoji)
  end

  pipeline :require_privileged_role_instances_delete do
    plug(:admin_api)
    plug(Pleroma.Web.Plugs.EnsurePrivilegedPlug, :instances_delete)
  end

  pipeline :require_privileged_role_moderation_log_read do
    plug(:admin_api)
    plug(Pleroma.Web.Plugs.EnsurePrivilegedPlug, :moderation_log_read)
  end

  pipeline :require_privileged_role_statistics_read do
    plug(:admin_api)
    plug(Pleroma.Web.Plugs.EnsurePrivilegedPlug, :statistics_read)
  end

  pipeline :require_privileged_role_announcements_manage_announcements do
    plug(:admin_api)
    plug(Pleroma.Web.Plugs.EnsurePrivilegedPlug, :announcements_manage_announcements)
  end

  pipeline :pleroma_html do
    plug(:browser)
    plug(:authenticate)
    plug(Pleroma.Web.Plugs.EnsureUserTokenAssignsPlug)
  end

  pipeline :well_known do
    plug(:accepts, ["json", "jrd+json", "xml", "xrd+xml"])
  end

  pipeline :config do
    plug(:accepts, ["json", "xml"])
    plug(OpenApiSpex.Plug.PutApiSpec, module: Pleroma.Web.ApiSpec)
  end

  pipeline :pleroma_api do
    plug(:accepts, ["html", "json"])
    plug(OpenApiSpex.Plug.PutApiSpec, module: Pleroma.Web.ApiSpec)
  end

  pipeline :mailbox_preview do
    plug(:accepts, ["html"])

    plug(:put_secure_browser_headers, %{
      "content-security-policy" =>
        "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' 'unsafe-eval'"
    })
  end

  pipeline :http_signature do
    plug(Pleroma.Web.Plugs.HTTPSignaturePlug)
    plug(Pleroma.Web.Plugs.MappedSignatureToIdentityPlug)
  end

  pipeline :static_fe do
    plug(Pleroma.Web.Plugs.StaticFEPlug)
  end

  scope "/api/v1/pleroma", Pleroma.Web.TwitterAPI do
    pipe_through(:pleroma_api)

    get("/password_reset/:token", PasswordController, :reset, as: :reset_password)
    post("/password_reset", PasswordController, :do_reset, as: :reset_password)
    get("/emoji", UtilController, :emoji)
    get("/captcha", UtilController, :captcha)
    get("/healthcheck", UtilController, :healthcheck)
    post("/remote_interaction", UtilController, :remote_interaction)
  end

  scope "/api/v1/pleroma", Pleroma.Web do
    pipe_through(:pleroma_api)
    post("/uploader_callback/:upload_path", UploaderController, :callback)
  end

  # AdminAPI: only admins can perform these actions
  scope "/api/v1/pleroma/admin", Pleroma.Web.AdminAPI do
    pipe_through([:admin_api, :require_admin])

    get("/users/:nickname/permission_group", AdminAPIController, :right_get)
    get("/users/:nickname/permission_group/:permission_group", AdminAPIController, :right_get)

    post("/users/:nickname/permission_group/:permission_group", AdminAPIController, :right_add)

    delete(
      "/users/:nickname/permission_group/:permission_group",
      AdminAPIController,
      :right_delete
    )

    post("/users/permission_group/:permission_group", AdminAPIController, :right_add_multiple)

    delete(
      "/users/permission_group/:permission_group",
      AdminAPIController,
      :right_delete_multiple
    )

    post("/users/follow", UserController, :follow)
    post("/users/unfollow", UserController, :unfollow)
    post("/users", UserController, :create)

    patch("/users/suggest", UserController, :suggest)
    patch("/users/unsuggest", UserController, :unsuggest)

    get("/relay", RelayController, :index)
    post("/relay", RelayController, :follow)
    delete("/relay", RelayController, :unfollow)

    get("/instance_document/:name", InstanceDocumentController, :show)
    patch("/instance_document/:name", InstanceDocumentController, :update)
    delete("/instance_document/:name", InstanceDocumentController, :delete)

    get("/config", ConfigController, :show)
    post("/config", ConfigController, :update)
    get("/config/descriptions", ConfigController, :descriptions)
    get("/need_reboot", AdminAPIController, :need_reboot)
    get("/restart", AdminAPIController, :restart)

    get("/oauth_app", OAuthAppController, :index)
    post("/oauth_app", OAuthAppController, :create)
    patch("/oauth_app/:id", OAuthAppController, :update)
    delete("/oauth_app/:id", OAuthAppController, :delete)

    get("/media_proxy_caches", MediaProxyCacheController, :index)
    post("/media_proxy_caches/delete", MediaProxyCacheController, :delete)
    post("/media_proxy_caches/purge", MediaProxyCacheController, :purge)

    get("/frontends", FrontendController, :index)
    post("/frontends/install", FrontendController, :install)

    post("/backups", AdminAPIController, :create_backup)
  end

  # AdminAPI: admins and mods (staff) can perform these actions (if privileged by role)
  scope "/api/v1/pleroma/admin", Pleroma.Web.AdminAPI do
    pipe_through(:require_privileged_role_announcements_manage_announcements)

    get("/announcements", AnnouncementController, :index)
    post("/announcements", AnnouncementController, :create)
    get("/announcements/:id", AnnouncementController, :show)
    patch("/announcements/:id", AnnouncementController, :change)
    delete("/announcements/:id", AnnouncementController, :delete)
  end

  # AdminAPI: admins and mods (staff) can perform these actions (if privileged by role)
  scope "/api/v1/pleroma/admin", Pleroma.Web.AdminAPI do
    pipe_through(:require_privileged_role_users_delete)

    delete("/users", UserController, :delete)
  end

lib/pleroma/web/o_auth/fallback_controller.ex
# Pleroma: A lightweight social networking server
# Copyright © 2017-2022 Pleroma Authors <https://pleroma.social/>
# SPDX-License-Identifier: AGPL-3.0-only

defmodule Pleroma.Web.OAuth.FallbackController do
  use Pleroma.Web, :controller
  alias Pleroma.Web.OAuth.OAuthController

  def call(conn, {:register, :generic_error}) do
    conn
    |> put_status(:internal_server_error)
    |> put_flash(
      :error,
      dgettext("errors", "Unknown error, please check the details and try again.")
    )
    |> OAuthController.registration_details(conn.params)
  end

  def call(conn, {:register, _error}) do
    conn
    |> put_status(:unauthorized)
    |> put_flash(:error, dgettext("errors", "Invalid Username/Password"))
    |> OAuthController.registration_details(conn.params)
  end

  def call(conn, _error) do
    conn
    |> put_status(:unauthorized)
    |> put_flash(:error, dgettext("errors", "Invalid Username/Password"))
    |> OAuthController.authorize(conn.params)
  end
end

lib/pleroma/web/o_auth/mfa_controller.ex
# Pleroma: A lightweight social networking server
# Copyright © 2017-2022 Pleroma Authors <https://pleroma.social/>
# SPDX-License-Identifier: AGPL-3.0-only

defmodule Pleroma.Web.OAuth.MFAController do
  @moduledoc """
  The model represents api to use Multi Factor authentications.
  """

  use Pleroma.Web, :controller

  alias Pleroma.MFA
  alias Pleroma.Web.Auth.TOTPAuthenticator
  alias Pleroma.Web.OAuth.MFAView, as: View
  alias Pleroma.Web.OAuth.OAuthController
  alias Pleroma.Web.OAuth.Token

  plug(:fetch_session when action in [:show, :verify])
  plug(:fetch_flash when action in [:show, :verify])

  @doc """
  Display form to input mfa code or recovery code.
  """
  def show(conn, %{"mfa_token" => mfa_token} = params) do
    template = Map.get(params, "challenge_type", "totp")

    conn
    |> put_view(View)
    |> render("#{template}.html", %{
      mfa_token: mfa_token,
      redirect_uri: params["redirect_uri"],
      state: params["state"]
    })
  end

  @doc """
  Verification code and continue authorization.
  """
  def verify(conn, %{"mfa" => %{"mfa_token" => mfa_token} = mfa_params} = _) do
    with {:ok, %{user: user, authorization: auth}} <- MFA.Token.validate(mfa_token),
         {:ok, _} <- validates_challenge(user, mfa_params) do
      conn
      |> OAuthController.after_create_authorization(auth, %{
        "authorization" => %{
          "redirect_uri" => mfa_params["redirect_uri"],
          "state" => mfa_params["state"]
        }
      })
    else
      _ ->
        conn
        |> put_flash(:error, "Two-factor authentication failed.")
        |> put_status(:unauthorized)
        |> show(mfa_params)
    end
  end

  @doc """
  Verification second step of MFA (or recovery) and returns access token.

  ## Endpoint
  POST /oauth/mfa/challenge

  params:
  `client_id`
  `client_secret`
  `mfa_token` - access token to check second step of mfa
  `challenge_type` - 'totp' or 'recovery'
  `code`

  """
  def challenge(conn, %{"mfa_token" => mfa_token} = params) do
    with {:ok, app} <- Token.Utils.fetch_app(conn),
         {:ok, %{user: user, authorization: auth}} <- MFA.Token.validate(mfa_token),
         {:ok, _} <- validates_challenge(user, params),
         {:ok, token} <- Token.exchange_token(app, auth) do
      OAuthController.after_token_exchange(conn, %{user: user, token: token})
    else
      _error ->
        conn
        |> put_status(400)
        |> json(%{error: "Invalid code"})
    end
  end

  # Verify TOTP Code
  defp validates_challenge(user, %{"challenge_type" => "totp", "code" => code} = _) do
    TOTPAuthenticator.verify(code, user)
  end

  # Verify Recovery Code
  defp validates_challenge(user, %{"challenge_type" => "recovery", "code" => code} = _) do
    TOTPAuthenticator.verify_recovery_code(user, code)
  end

  defp validates_challenge(_, _), do: {:error, :unsupported_challenge_type}
end

lib/pleroma/web/o_auth/mfa_view.ex
# Pleroma: A lightweight social networking server
# Copyright © 2017-2022 Pleroma Authors <https://pleroma.social/>
# SPDX-License-Identifier: AGPL-3.0-only

defmodule Pleroma.Web.OAuth.MFAView do
  use Pleroma.Web, :view
  import Phoenix.HTML.Form
  alias Pleroma.MFA
  alias Pleroma.Web.Gettext

  def render("mfa_response.json", %{token: token, user: user}) do
    %{
      error: "mfa_required",
      mfa_token: token.token,
      supported_challenge_types: MFA.supported_methods(user)
    }
  end
end

lib/pleroma/web/o_auth/o_auth_view.ex
# Pleroma: A lightweight social networking server
# Copyright © 2017-2022 Pleroma Authors <https://pleroma.social/>
# SPDX-License-Identifier: AGPL-3.0-only

defmodule Pleroma.Web.OAuth.OAuthView do
  use Pleroma.Web, :view
  import Phoenix.HTML.Form
  import Phoenix.HTML
  alias Pleroma.Web.Gettext

  alias Pleroma.Web.OAuth.Token.Utils

  def render("token.json", %{token: token} = opts) do
    response = %{
      id: token.id,
      token_type: "Bearer",
      access_token: token.token,
      refresh_token: token.refresh_token,
      expires_in: NaiveDateTime.diff(token.valid_until, NaiveDateTime.utc_now()),
      scope: Enum.join(token.scopes, " "),
      created_at: Utils.format_created_at(token)
    }

    if user = opts[:user] do
      response
      |> Map.put(:me, user.ap_id)
    else
      response
    end
  end
end

lib/pleroma/web/templates/o_auth/o_auth/_scopes.html.eex
<div class="scopes-input">
  <%= label @form, :scope, Gettext.dpgettext("static_pages", "oauth scopes message", "The following permissions will be granted") %>
  <div class="scopes">
    <%= for scope <- @available_scopes do %>
      <%# Note: using hidden input with `unchecked_value` in order to distinguish user's empty selection from `scope` param being omitted %>
      <%= if scope in @scopes do %>
        <div class="scope">
          <%= checkbox @form, :"scope_#{scope}", value: scope in @scopes && scope, checked_value: scope, unchecked_value: "", name: "authorization[scope][]" %>
          <%= label @form, :"scope_#{scope}", String.capitalize(scope) %>
          <%= if scope in @scopes && scope do %>
            <%= String.capitalize(scope) %>
          <% end %>
        </div>
      <% else %>
        <%= checkbox @form, :"scope_#{scope}", value: scope in @scopes && scope, checked_value: scope, unchecked_value: "", name: "authorization[scope][]" %>
      <% end %>
    <% end %>
  </div>
</div>

lib/pleroma/web/templates/o_auth/o_auth/consumer.html.eex
<h2><%= Gettext.dpgettext("static_pages", "oauth external provider page title", "Sign in with external provider") %></h2>

<%= form_for @conn, Routes.o_auth_path(@conn, :prepare_request), [as: "authorization", method: "get"], fn f -> %>
  <div style="display: none">
    <%= render Phoenix.Controller.view_module(@conn), "_scopes.html", Map.merge(assigns, %{form: f}) %>
  </div>

  <%= hidden_input f, :client_id, value: @client_id %>
  <%= hidden_input f, :redirect_uri, value: @redirect_uri %>
  <%= hidden_input f, :state, value: @state %>

    <%= for strategy <- Pleroma.Config.oauth_consumer_strategies() do %>
      <%= submit Gettext.dpgettext("static_pages", "oauth external provider sign in button", "Sign in with %{strategy}", strategy: String.capitalize(strategy)), name: "provider", value: strategy %>
    <% end %>
<% end %>

lib/pleroma/web/templates/o_auth/o_auth/oob_authorization_created.html.eex
<h1><%= Gettext.dpgettext("static_pages", "oauth authorized page title", "Successfully authorized") %></h1>
<h2><%= raw Gettext.dpgettext("static_pages", "oauth token code message", "Token code is <br>%{token}", token: safe_to_string(html_escape(@auth.token))) %></h2>

lib/pleroma/web/templates/o_auth/o_auth/oob_token_exists.html.eex
<h1><%= Gettext.dpgettext("static_pages", "oauth authorization exists page title", "Authorization exists") %></h1>
<h2><%= raw Gettext.dpgettext("static_pages", "oauth token code message", "Token code is <br>%{token}", token: safe_to_string(html_escape(@token.token))) %></h2>

lib/pleroma/web/templates/o_auth/o_auth/register.html.eex
<%= if get_flash(@conn, :info) do %>
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
<% end %>
<%= if get_flash(@conn, :error) do %>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
<% end %>

<h2><%= Gettext.dpgettext("static_pages", "oauth register page title", "Registration Details") %></h2>

<p><%= Gettext.dpgettext("static_pages", "oauth register page fill form prompt", "If you'd like to register a new account, please provide the details below.") %></p>
<%= form_for @conn, Routes.o_auth_path(@conn, :register), [as: "authorization"], fn f -> %>

<div class="input">
  <%= label f, :nickname, Gettext.dpgettext("static_pages", "oauth register page nickname prompt", "Nickname") %>
  <%= text_input f, :nickname, value: @nickname, autocomplete: "username" %>
</div>
<div class="input">
  <%= label f, :email, Gettext.dpgettext("static_pages", "oauth register page email prompt", "Email") %>
  <%= text_input f, :email, value: @email, autocomplete: "email" %>
</div>

<%= submit Gettext.dpgettext("static_pages", "oauth register page register button", "Proceed as new user"), name: "op", value: "register" %>

<p><%= Gettext.dpgettext("static_pages", "oauth register page login prompt", "Alternatively, sign in to connect to existing account.") %></p>

<div class="input">
  <%= label f, :name, Gettext.dpgettext("static_pages", "oauth register page login username prompt", "Name or email") %>
  <%= text_input f, :name, autocomplete: "username" %>
</div>
<div class="input">
  <%= label f, :password, Gettext.dpgettext("static_pages", "oauth register page login password prompt", "Password") %>
  <%= password_input f, :password, autocomplete: "password" %>
</div>

<%= submit Gettext.dpgettext("static_pages", "oauth register page login button", "Proceed as existing user"), name: "op", value: "connect" %>

<%= hidden_input f, :client_id, value: @client_id %>
<%= hidden_input f, :redirect_uri, value: @redirect_uri %>
<%= hidden_input f, :scope, value: Enum.join(@scopes, " ") %>
<%= hidden_input f, :state, value: @state %>

<% end %>

lib/pleroma/web/templates/o_auth/o_auth/show.html.eex
<%= if get_flash(@conn, :info) do %>
<p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
<% end %>
<%= if get_flash(@conn, :error) do %>
<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
<% end %>

<%= form_for @conn, Routes.o_auth_path(@conn, :authorize), [as: "authorization"], fn f -> %>

<%= if @user do %>
  <div class="account-header">
    <div class="account-header__banner" style="background-image: url('<%= Pleroma.User.banner_url(@user) %>')"></div>
    <div class="account-header__avatar" style="background-image: url('<%= Pleroma.User.avatar_url(@user) %>')"></div>
    <div class="account-header__meta">
      <div class="account-header__display-name"><%= @user.name %></div>
      <div class="account-header__nickname">@<%= @user.nickname %>@<%= Pleroma.User.get_host(@user) %></div>
    </div>
  </div>
<% end %>

<div class="container__content">
  <%= if @app do %>
    <p><%= raw Gettext.dpgettext("static_pages", "oauth authorize message", "Application <strong>%{client_name}</strong> is requesting access to your account.", client_name: safe_to_string(html_escape(@app.client_name))) %></p>
    <%= render Phoenix.Controller.view_module(@conn), "_scopes.html", Map.merge(assigns, %{form: f}) %>
  <% end %>

  <%= if @user do %>
    <div class="actions">
      <a class="button button--cancel" href="/">
        <%= Gettext.dpgettext("static_pages", "oauth authorize cancel button", "Cancel") %>
      </a>
      <%= submit Gettext.dpgettext("static_pages", "oauth authorize approve button", "Approve"), class: "button--approve" %>
    </div>
  <% else %>
    <%= if @params["registration"] in ["true", true] do %>
      <h3><%= Gettext.dpgettext("static_pages", "oauth register page title", "This is the first time you visit! Please enter your Pleroma handle.") %></h3>
      <p><%= Gettext.dpgettext("static_pages", "oauth register nickname unchangeable warning", "Choose carefully! You won't be able to change this later. You will be able to change your display name, though.") %></p>
      <div class="input">
        <%= label f, :nickname, Gettext.dpgettext("static_pages", "oauth register nickname prompt", "Pleroma Handle") %>
        <%= text_input f, :nickname, placeholder: "lain", autocomplete: "username" %>
      </div>
      <%= hidden_input f, :name, value: @params["name"] %>
      <%= hidden_input f, :password, value: @params["password"] %>
      <br>
    <% else %>
      <div class="input">
        <%= label f, :name, Gettext.dpgettext("static_pages", "oauth login username prompt", "Username") %>
        <%= text_input f, :name %>
      </div>
      <div class="input">
        <%= label f, :password, Gettext.dpgettext("static_pages", "oauth login password prompt", "Password") %>
        <%= password_input f, :password %>
      </div>
      <%= submit Gettext.dpgettext("static_pages", "oauth login button", "Log In") %>
    <% end %>
  <% end %>
</div>

<%= hidden_input f, :client_id, value: @client_id %>
<%= hidden_input f, :response_type, value: @response_type %>
<%= hidden_input f, :redirect_uri, value: @redirect_uri %>
<%= hidden_input f, :state, value: @state %>
<% end %>

<%= if Pleroma.Config.oauth_consumer_enabled?() do %>
  <%= render Phoenix.Controller.view_module(@conn), Pleroma.Web.Auth.WrapperAuthenticator.oauth_consumer_template(), assigns %>
<% end %>