lib/pleroma/web/router.ex
    post("/statuses/:id/unmute", StatusController, :unmute_conversation)

    post("/push/subscription", SubscriptionController, :create)
    get("/push/subscription", SubscriptionController, :show)
    put("/push/subscription", SubscriptionController, :update)
    delete("/push/subscription", SubscriptionController, :delete)

    get("/suggestions", SuggestionController, :index)
    delete("/suggestions/:account_id", SuggestionController, :dismiss)

    get("/timelines/home", TimelineController, :home)
    get("/timelines/direct", TimelineController, :direct)
    get("/timelines/list/:list_id", TimelineController, :list)

    get("/announcements", AnnouncementController, :index)
    post("/announcements/:id/dismiss", AnnouncementController, :mark_read)
  end

  scope "/api/v1", Pleroma.Web.MastodonAPI do
    pipe_through(:app_api)

    post("/apps", AppController, :create)
    get("/apps/verify_credentials", AppController, :verify_credentials)
  end

  scope "/api/v1", Pleroma.Web.MastodonAPI do
    pipe_through(:api)

    get("/accounts/search", SearchController, :account_search)
    get("/search", SearchController, :search)

    get("/accounts/lookup", AccountController, :lookup)

    get("/accounts/:id/statuses", AccountController, :statuses)
    get("/accounts/:id/followers", AccountController, :followers)
    get("/accounts/:id/following", AccountController, :following)
    get("/accounts/:id", AccountController, :show)

    post("/accounts", AccountController, :create)

    get("/instance", InstanceController, :show)
    get("/instance/peers", InstanceController, :peers)

    get("/statuses", StatusController, :index)
    get("/statuses/:id", StatusController, :show)
    get("/statuses/:id/context", StatusController, :context)
    get("/statuses/:id/card", StatusController, :card)
    get("/statuses/:id/favourited_by", StatusController, :favourited_by)
    get("/statuses/:id/reblogged_by", StatusController, :reblogged_by)
    get("/statuses/:id/history", StatusController, :show_history)
    get("/statuses/:id/source", StatusController, :show_source)

    get("/custom_emojis", CustomEmojiController, :index)

    get("/trends", MastodonAPIController, :empty_array)

    get("/timelines/public", TimelineController, :public)
    get("/timelines/tag/:tag", TimelineController, :hashtag)

    get("/polls/:id", PollController, :show)

    get("/directory", DirectoryController, :index)
  end

  scope "/api/v2", Pleroma.Web.MastodonAPI do
    pipe_through(:api)
    get("/search", SearchController, :search2)

    post("/media", MediaController, :create2)

    get("/suggestions", SuggestionController, :index2)
  end

  scope "/api", Pleroma.Web do
    pipe_through(:config)

    get("/pleroma/frontend_configurations", TwitterAPI.UtilController, :frontend_configurations)
  end

  scope "/api", Pleroma.Web do
    pipe_through(:api)

    get(
      "/account/confirm_email/:user_id/:token",
      TwitterAPI.Controller,
      :confirm_email,
      as: :confirm_email
    )
  end

  scope "/api" do
    pipe_through(:base_api)

    get("/openapi", OpenApiSpex.Plug.RenderSpec, [])
  end

  scope "/api", Pleroma.Web, as: :authenticated_twitter_api do
    pipe_through(:authenticated_api)

    get("/oauth_tokens", TwitterAPI.Controller, :oauth_tokens)
    delete("/oauth_tokens/:id", TwitterAPI.Controller, :revoke_token)
  end

  scope "/", Pleroma.Web do
    # Note: html format is supported only if static FE is enabled
    # Note: http signature is only considered for json requests (no auth for non-json requests)
    pipe_through([:accepts_html_json, :http_signature, :static_fe])

    get("/objects/:uuid", OStatus.OStatusController, :object)
    get("/activities/:uuid", OStatus.OStatusController, :activity)
    get("/notice/:id", OStatus.OStatusController, :notice)

    # Mastodon compatibility routes
    get("/users/:nickname/statuses/:id", OStatus.OStatusController, :object)
    get("/users/:nickname/statuses/:id/activity", OStatus.OStatusController, :activity)
  end

  scope "/", Pleroma.Web do
    # Note: html format is supported only if static FE is enabled
    # Note: http signature is only considered for json requests (no auth for non-json requests)
    pipe_through([:accepts_html_xml_json, :http_signature, :static_fe])

    # Note: returns user _profile_ for json requests, redirects to user _feed_ for non-json ones
    get("/users/:nickname", Feed.UserController, :feed_redirect, as: :user_feed)
  end

  scope "/", Pleroma.Web do
    # Note: html format is supported only if static FE is enabled
    pipe_through([:accepts_html_xml, :static_fe])

    get("/users/:nickname/feed", Feed.UserController, :feed, as: :user_feed)
  end

  scope "/", Pleroma.Web do
    pipe_through(:accepts_html)
    get("/notice/:id/embed_player", OStatus.OStatusController, :notice_player)
  end

  scope "/", Pleroma.Web do
    pipe_through(:accepts_xml_rss_atom)
    get("/tags/:tag", Feed.TagController, :feed, as: :tag_feed)
  end

  scope "/", Pleroma.Web do
    pipe_through(:browser)
    get("/mailer/unsubscribe/:token", Mailer.SubscriptionController, :unsubscribe)
  end

  pipeline :ap_service_actor do
    plug(:accepts, ["activity+json", "json"])
  end

  # Server to Server (S2S) AP interactions
  pipeline :activitypub do
    plug(:ap_service_actor)
    plug(:http_signature)
  end

  # Client to Server (C2S) AP interactions
  pipeline :activitypub_client do
    plug(:ap_service_actor)
    plug(:fetch_session)
    plug(:authenticate)
    plug(:after_auth)
  end

  scope "/", Pleroma.Web.ActivityPub do
    pipe_through([:activitypub_client])

    get("/api/ap/whoami", ActivityPubController, :whoami)
    get("/users/:nickname/inbox", ActivityPubController, :read_inbox)

    get("/users/:nickname/outbox", ActivityPubController, :outbox)
    post("/users/:nickname/outbox", ActivityPubController, :update_outbox)
    post("/api/ap/upload_media", ActivityPubController, :upload_media)

    # The following two are S2S as well, see `ActivityPub.fetch_follow_information_for_user/1`:
    get("/users/:nickname/followers", ActivityPubController, :followers)
    get("/users/:nickname/following", ActivityPubController, :following)
    get("/users/:nickname/collections/featured", ActivityPubController, :pinned)
  end

  scope "/", Pleroma.Web.ActivityPub do
    pipe_through(:activitypub)
    post("/inbox", ActivityPubController, :inbox)
    post("/users/:nickname/inbox", ActivityPubController, :inbox)
  end

  scope "/relay", Pleroma.Web.ActivityPub do
    pipe_through(:ap_service_actor)

    get("/", ActivityPubController, :relay)

    scope [] do
      pipe_through(:http_signature)
      post("/inbox", ActivityPubController, :inbox)
    end

    get("/following", ActivityPubController, :relay_following)
    get("/followers", ActivityPubController, :relay_followers)
  end

  scope "/internal/fetch", Pleroma.Web.ActivityPub do
    pipe_through(:ap_service_actor)

    get("/", ActivityPubController, :internal_fetch)
    post("/inbox", ActivityPubController, :inbox)
  end

  scope "/.well-known", Pleroma.Web do
    pipe_through(:well_known)

    get("/host-meta", WebFinger.WebFingerController, :host_meta)
    get("/webfinger", WebFinger.WebFingerController, :webfinger)
    get("/nodeinfo", Nodeinfo.NodeinfoController, :schemas)
  end

  scope "/nodeinfo", Pleroma.Web do
    get("/:version", Nodeinfo.NodeinfoController, :nodeinfo)
  end

  scope "/", Pleroma.Web do
    pipe_through(:api)

    get("/manifest.json", ManifestController, :show)
  end

  scope "/", Pleroma.Web do
    pipe_through(:pleroma_html)

    post("/auth/password", TwitterAPI.PasswordController, :request)
  end

  scope "/proxy/", Pleroma.Web do
    get("/preview/:sig/:url", MediaProxy.MediaProxyController, :preview)
    get("/preview/:sig/:url/:filename", MediaProxy.MediaProxyController, :preview)
    get("/:sig/:url", MediaProxy.MediaProxyController, :remote)
    get("/:sig/:url/:filename", MediaProxy.MediaProxyController, :remote)
  end

  if Pleroma.Config.get(:env) == :dev do
    scope "/dev" do
      pipe_through([:mailbox_preview])

      forward("/mailbox", Plug.Swoosh.MailboxPreview, base_path: "/dev/mailbox")
    end
  end

  scope "/" do
    pipe_through([:pleroma_html, :authenticate, :require_admin])
    live_dashboard("/phoenix/live_dashboard")
  end

  # Test-only routes needed to test action dispatching and plug chain execution
  if Pleroma.Config.get(:env) == :test do
    @test_actions [
      :do_oauth_check,
      :fallback_oauth_check,
      :skip_oauth_check,
      :fallback_oauth_skip_publicity_check,
      :skip_oauth_skip_publicity_check,
      :missing_oauth_check_definition
    ]

    scope "/test/api", Pleroma.Tests do
      pipe_through(:api)

      for action <- @test_actions do
        get("/#{action}", AuthTestController, action)
      end
    end

    scope "/test/authenticated_api", Pleroma.Tests do
      pipe_through(:authenticated_api)

      for action <- @test_actions do
        get("/#{action}", AuthTestController, action)
      end
    end
  end

  scope "/", Pleroma.Web.MongooseIM do
    get("/user_exists", MongooseIMController, :user_exists)
    get("/check_password", MongooseIMController, :check_password)
  end

  scope "/", Pleroma.Web.Fallback do
    get("/registration/:token", RedirectController, :registration_page)
    get("/:maybe_nickname_or_id", RedirectController, :redirector_with_meta)
    match(:*, "/api/pleroma*path", LegacyPleromaApiRerouterPlug, [])
    get("/api*path", RedirectController, :api_not_implemented)
    get("/*path", RedirectController, :redirector_with_preload)

    options("/*path", RedirectController, :empty)
  end

  # TODO: Change to Phoenix.Router.routes/1 for Phoenix 1.6.0+
  def get_api_routes do
    __MODULE__.__routes__()
    |> Enum.reject(fn r -> r.plug == Pleroma.Web.Fallback.RedirectController end)
    |> Enum.map(fn r ->
      r.path
      |> String.split("/", trim: true)
      |> List.first()
    end)

lib/pleroma/web/feed/feed_view.ex
# Pleroma: A lightweight social networking server
# Copyright © 2017-2022 Pleroma Authors <https://pleroma.social/>
# SPDX-License-Identifier: AGPL-3.0-only

defmodule Pleroma.Web.Feed.FeedView do
  use Phoenix.HTML
  use Pleroma.Web, :view

  alias Pleroma.Formatter
  alias Pleroma.Object
  alias Pleroma.User
  alias Pleroma.Web.Gettext
  alias Pleroma.Web.MediaProxy

  require Pleroma.Constants

  @days ~w(Mon Tue Wed Thu Fri Sat Sun)
  @months ~w(Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec)

  def prepare_activity(activity, opts \\ []) do
    object = Object.normalize(activity, fetch: false)

    actor =
      if opts[:actor] do
        Pleroma.User.get_cached_by_ap_id(activity.actor)
      end

    %{
      activity: activity,
      object: object,
      data: Map.get(object, :data),
      actor: actor
    }
  end

  def most_recent_update(activities) do
    with %{updated_at: updated_at} <- List.first(activities) do
      to_rfc3339(updated_at)
    end
  end

  def most_recent_update(activities, user, :atom) do
    (List.first(activities) || user).updated_at
    |> to_rfc3339()
  end

  def most_recent_update(activities, user, :rss) do
    (List.first(activities) || user).updated_at
    |> to_rfc2822()
  end

  def feed_logo do
    case Pleroma.Config.get([:feed, :logo]) do
      nil ->
        "#{Pleroma.Web.Endpoint.url()}/static/logo.svg"

      logo ->
        "#{Pleroma.Web.Endpoint.url()}#{logo}"
    end
    |> MediaProxy.url()
  end

  def email(user) do
    user.nickname <> "@" <> Pleroma.Web.Endpoint.host()
  end

  def logo(user) do
    user
    |> User.avatar_url()
    |> MediaProxy.url()
  end

  def last_activity(activities), do: List.last(activities)

  def activity_title(%{"content" => content, "summary" => summary} = data, opts \\ %{}) do
    title =
      cond do
        summary != "" -> summary
        content != "" -> activity_content(data)
        true -> "a post"
      end

    title
    |> Pleroma.Web.Metadata.Utils.scrub_html()
    |> Pleroma.Emoji.Formatter.demojify()
    |> Formatter.truncate(opts[:max_length], opts[:omission])
  end

  def activity_description(data) do
    content = activity_content(data)
    summary = data["summary"]

    cond do
      content != "" -> escape(content)
      summary != "" -> escape(summary)
      true -> escape(data["type"])
    end
  end

  def activity_content(%{"content" => content}) do
    content
    |> String.replace(~r/[\n\r]/, "")
  end

  def activity_content(_), do: ""

  def activity_context(activity), do: escape(activity.data["context"])

  def attachment_href(attachment) do
    attachment["url"]
    |> hd()
    |> Map.get("href")
  end

  def attachment_type(attachment) do
    attachment["url"]
    |> hd()
    |> Map.get("mediaType")
  end

  def get_href(id) do
    with %Object{data: %{"external_url" => external_url}} <- Object.get_cached_by_ap_id(id) do
      external_url
    else
      _e -> id
    end
  end

  def escape(html) do
    html
    |> html_escape()
    |> safe_to_string()
  end

  @spec to_rfc3339(String.t() | NativeDateTime.t()) :: String.t()
  def to_rfc3339(date) when is_binary(date) do
    date
    |> Timex.parse!("{ISO:Extended}")
    |> to_rfc3339()
  end

  def to_rfc3339(nd) do
    nd
    |> Timex.to_datetime()
    |> Timex.format!("{RFC3339}")
  end

  @spec to_rfc2822(String.t() | DateTime.t() | NativeDateTime.t()) :: String.t()
  def to_rfc2822(datestr) when is_binary(datestr) do
    datestr
    |> Timex.parse!("{ISO:Extended}")
    |> to_rfc2822()
  end

  def to_rfc2822(%DateTime{} = date) do
    date
    |> DateTime.to_naive()
    |> NaiveDateTime.to_erl()
    |> rfc2822_from_erl()
  end

  def to_rfc2822(nd) do
    nd
    |> Timex.to_datetime()
    |> DateTime.to_naive()
    |> NaiveDateTime.to_erl()
    |> rfc2822_from_erl()
  end

  @doc """
  Builds a RFC2822 timestamp from an Erlang timestamp
  [RFC2822 3.3 - Date and Time Specification](https://tools.ietf.org/html/rfc2822#section-3.3)
  This function always assumes the Erlang timestamp is in Universal time, not Local time
  """
  def rfc2822_from_erl({{year, month, day} = date, {hour, minute, second}}) do
    day_name = Enum.at(@days, :calendar.day_of_the_week(date) - 1)
    month_name = Enum.at(@months, month - 1)

    date_part = "#{day_name}, #{day} #{month_name} #{year}"
    time_part = "#{pad(hour)}:#{pad(minute)}:#{pad(second)}"

    date_part <> " " <> time_part <> " +0000"
  end

  defp pad(num) do
    num
    |> Integer.to_string()
    |> String.pad_leading(2, "0")
  end
end

lib/pleroma/web/feed/tag_controller.ex
# Pleroma: A lightweight social networking server
# Copyright © 2017-2022 Pleroma Authors <https://pleroma.social/>
# SPDX-License-Identifier: AGPL-3.0-only

defmodule Pleroma.Web.Feed.TagController do
  use Pleroma.Web, :controller

  alias Pleroma.Config
  alias Pleroma.Web.ActivityPub.ActivityPub
  alias Pleroma.Web.Feed.FeedView

  def feed(conn, params) do
    if Config.get!([:instance, :public]) do
      render_feed(conn, params)
    else
      render_error(conn, :not_found, "Not found")
    end
  end

  defp render_feed(conn, %{"tag" => raw_tag} = params) do
    {format, tag} = parse_tag(raw_tag)

    activities =
      %{type: ["Create"], tag: tag}
      |> Pleroma.Maps.put_if_present(:max_id, params["max_id"])
      |> ActivityPub.fetch_public_activities()

    conn
    |> put_resp_content_type("application/#{format}+xml")
    |> put_view(FeedView)
    |> render("tag.#{format}",
      activities: activities,
      tag: tag,
      feed_config: Config.get([:feed])
    )
  end

  @spec parse_tag(binary() | any()) :: {format :: String.t(), tag :: String.t()}
  defp parse_tag(raw_tag) do
    case is_binary(raw_tag) && Enum.reverse(String.split(raw_tag, ".")) do
      [format | tag] when format in ["rss", "atom"] ->
        {format, Enum.join(tag, ".")}

      _ ->
        {"atom", raw_tag}
    end
  end
end

lib/pleroma/web/templates/feed/feed/_activity.atom.eex
<entry>
  <activity:object-type>http://activitystrea.ms/schema/1.0/note</activity:object-type>
  <activity:verb>http://activitystrea.ms/schema/1.0/post</activity:verb>
  <id><%= @data["id"] %></id>
  <title><%= activity_title(@data, Keyword.get(@feed_config, :post_title, %{})) %></title>
  <content type="html"><%= activity_description(@data) %></content>
  <published><%= to_rfc3339(@activity.data["published"]) %></published>
  <updated><%= to_rfc3339(@activity.data["published"]) %></updated>
  <ostatus:conversation ref="<%= activity_context(@activity) %>">
    <%= activity_context(@activity) %>
  </ostatus:conversation>
  <link href="<%= activity_context(@activity) %>" rel="ostatus:conversation"/>

  <%= if @data["summary"] != "" do %>
    <summary><%= escape(@data["summary"]) %></summary>
  <% end %>

  <%= if @activity.local do %>
    <link type="application/atom+xml" href='<%= @data["id"] %>' rel="self"/>
    <link type="text/html" href='<%= @data["id"] %>' rel="alternate"/>
  <% else %>
    <link type="text/html" href='<%= @data["external_url"] %>' rel="alternate"/>
  <% end %>

  <%= for tag <- Pleroma.Object.hashtags(@object) do %>
    <category term="<%= tag %>"></category>
  <% end %>

  <%= for attachment <- @data["attachment"] || [] do %>
    <link rel="enclosure" href="<%= attachment_href(attachment) %>" type="<%= attachment_type(attachment) %>"/>
  <% end %>

  <%= if @data["inReplyTo"] do %>
    <thr:in-reply-to ref='<%= @data["inReplyTo"] %>' href='<%= get_href(@data["inReplyTo"]) %>'/>
  <% end %>

  <%= for id <- @activity.recipients do %>
    <%= if id == Pleroma.Constants.as_public() do %>
      <link rel="mentioned" ostatus:object-type="http://activitystrea.ms/schema/1.0/collection" href="http://activityschema.org/collection/public"/>
    <% else %>
      <%= unless Regex.match?(~r/^#{Pleroma.Web.Endpoint.url()}.+followers$/, id) do %>
        <link rel="mentioned" ostatus:object-type="http://activitystrea.ms/schema/1.0/person" href="<%= id %>"/>
      <% end %>
    <% end %>
  <% end %>

  <%= for {emoji, file} <- @data["emoji"] || %{} do %>
    <link name="<%= emoji %>" rel="emoji" href="<%= file %>"/>
  <% end %>
</entry>

lib/pleroma/web/templates/feed/feed/_activity.rss.eex
<item>
  <activity:object-type>http://activitystrea.ms/schema/1.0/note</activity:object-type>
  <activity:verb>http://activitystrea.ms/schema/1.0/post</activity:verb>
  <guid><%= @data["id"] %></guid>
  <title><%= activity_title(@data, Keyword.get(@feed_config, :post_title, %{})) %></title>
  <description><%= activity_description(@data) %></description>
  <pubDate><%= to_rfc2822(@activity.data["published"]) %></pubDate>
  <ostatus:conversation ref="<%= activity_context(@activity) %>">
    <%= activity_context(@activity) %>
  </ostatus:conversation>

  <%= if @activity.local do %>
    <link><%= @data["id"] %></link>
  <% else %>
    <link><%= @data["external_url"] %></link>
  <% end %>

  <link rel="ostatus:conversation"><%= activity_context(@activity) %></link>

  <%= for tag <- Pleroma.Object.hashtags(@object) do %>
    <category term="<%= tag %>"></category>
  <% end %>

  <%= for attachment <- @data["attachment"] || [] do %>
    <enclosure url="<%= attachment_href(attachment) %>" type="<%= attachment_type(attachment) %>" />
  <% end %>

  <%= if @data["inReplyTo"] do %>
    <thr:in-reply-to ref='<%= @data["inReplyTo"] %>' href='<%= get_href(@data["inReplyTo"]) %>'/>
  <% end %>

  <%= for id <- @activity.recipients do %>
    <%= if id == Pleroma.Constants.as_public() do %>
      <link rel="mentioned" ostatus:object-type="http://activitystrea.ms/schema/1.0/collection">http://activityschema.org/collection/public</link>
    <% else %>
      <%= unless Regex.match?(~r/^#{Pleroma.Web.Endpoint.url()}.+followers$/, id) do %>
        <link rel="mentioned" ostatus:object-type="http://activitystrea.ms/schema/1.0/person"><%= id %></link>
      <% end %>
    <% end %>
  <% end %>

  <%= for {emoji, file} <- @data["emoji"] || %{} do %>
    <link name="<%= emoji %>" rel="emoji"><%= file %></link>
  <% end %>
</item>

lib/pleroma/web/templates/feed/feed/_author.atom.eex
<author>
  <uri><%= @user.ap_id %></uri>
  <name><%= @user.nickname %></name>
  <activity:object>http://activitystrea.ms/schema/1.0/person</activity:object>
  <activity:displayName><%= @user.name %></activity:displayName>
  <activity:image><%= User.avatar_url(@user) %></activity:image>
  <activity:id><%= @user.ap_id %></activity:id>
  <activity:published><%= to_rfc3339(@user.inserted_at) %></activity:published>
  <activity:updated><%= to_rfc3339(@user.updated_at) %></activity:updated>
  <activity:url><%= @user.ap_id %></activity:url>
  <poco:preferredUsername><%= @user.nickname %></poco:preferredUsername>
  <poco:displayName><%= @user.name %></poco:displayName>
  <poco:note><%= escape(@user.bio) %></poco:note>
</author>

lib/pleroma/web/templates/feed/feed/tag.atom.eex
<?xml version="1.0" encoding="UTF-8"?>
<feed
  xmlns="http://www.w3.org/2005/Atom"
  xmlns:thr="http://purl.org/syndication/thread/1.0"
  xmlns:activity="http://activitystrea.ms/spec/1.0/"
  xmlns:poco="http://portablecontacts.net/spec/1.0"
  xmlns:ostatus="http://ostatus.org/schema/1.0"
  xmlns:statusnet="http://status.net/schema/api/1/">

  <id><%= Routes.tag_feed_url(@conn, :feed, @tag) <> ".atom" %></id>
  <title>#<%= @tag %></title>
  <subtitle><%= Gettext.dpgettext("static_pages", "tag feed description", "These are public toots tagged with #%{tag}. You can interact with them if you have an account anywhere in the fediverse.", tag: @tag) %></subtitle>
  <logo><%= feed_logo() %></logo>
  <updated><%= most_recent_update(@activities) %></updated>
  <link rel="self" href="<%= '#{Routes.tag_feed_url(@conn, :feed, @tag)}.atom'  %>" type="application/atom+xml"/>

  <%= for activity <- @activities do %>
  <%= render Phoenix.Controller.view_module(@conn), "_tag_activity.atom", Map.merge(assigns, prepare_activity(activity, actor: true)) %>
  <% end %>
</feed>

lib/pleroma/web/templates/feed/feed/tag.rss.eex
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"
     xmlns:webfeeds="http://webfeeds.org/rss/1.0"
     xmlns:thr="http://purl.org/syndication/thread/1.0">
  <channel>

    <title>#<%= @tag %></title>
    <description><%= Gettext.dpgettext("static_pages", "tag feed description", "These are public toots tagged with #%{tag}. You can interact with them if you have an account anywhere in the fediverse.", tag: @tag) %></description>
    <link><%= '#{Routes.tag_feed_url(@conn, :feed, @tag)}.rss' %></link>
    <webfeeds:logo><%= feed_logo() %></webfeeds:logo>
    <webfeeds:accentColor>2b90d9</webfeeds:accentColor>
    <%= for activity <- @activities do %>
    <%= render Phoenix.Controller.view_module(@conn), "_tag_activity.xml", Map.merge(assigns, prepare_activity(activity)) %>
    <% end %>
  </channel>
</rss>

lib/pleroma/web/templates/feed/feed/user.atom.eex
<?xml version="1.0" encoding="UTF-8"?>
<feed
  xmlns="http://www.w3.org/2005/Atom"
  xmlns:thr="http://purl.org/syndication/thread/1.0"
  xmlns:activity="http://activitystrea.ms/spec/1.0/"
  xmlns:poco="http://portablecontacts.net/spec/1.0"
  xmlns:ostatus="http://ostatus.org/schema/1.0">

  <id><%= Routes.user_feed_url(@conn, :feed, @user.nickname) <> ".atom" %></id>
  <title><%= @user.nickname <> "'s timeline" %></title>
  <subtitle><%= escape(@user.bio) %></subtitle>
  <updated><%= most_recent_update(@activities, @user, :atom) %></updated>
  <logo><%= logo(@user) %></logo>
  <link rel="self" href="<%= '#{Routes.user_feed_url(@conn, :feed, @user.nickname)}.atom' %>" type="application/atom+xml"/>

  <%= render Phoenix.Controller.view_module(@conn), "_author.atom", assigns %>

  <%= if last_activity(@activities) do %>
    <link rel="next" href="<%= '#{Routes.user_feed_url(@conn, :feed, @user.nickname)}.atom?max_id=#{last_activity(@activities).id}' %>" type="application/atom+xml"/>
  <% end %>

  <%= for activity <- @activities do %>
  <%= render Phoenix.Controller.view_module(@conn), "_activity.atom", Map.merge(assigns, prepare_activity(activity)) %>
  <% end %>
</feed>

lib/pleroma/web/templates/feed/feed/user.rss.eex
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0"
     xmlns:atom="http://www.w3.org/2005/Atom"
     xmlns:thr="http://purl.org/syndication/thread/1.0"
     xmlns:activity="http://activitystrea.ms/spec/1.0/"
     xmlns:ostatus="http://ostatus.org/schema/1.0"
     xmlns:poco="http://portablecontacts.net/spec/1.0">
  <channel>
    <title><%= @user.nickname <> "'s timeline" %></title>
    <link><%= '#{Routes.user_feed_url(@conn, :feed, @user.nickname)}.rss' %></link>
    <atom:link href="<%= Routes.user_feed_url(@conn, :feed, @user.nickname) <> ".atom" %>"
               rel="self" type="application/rss+xml" />
    <description><%= escape(@user.bio) %></description>
    <image>
      <url><%= logo(@user) %></url>
      <title><%= @user.nickname <> "'s timeline" %></title>
      <link><%= '#{Routes.user_feed_url(@conn, :feed, @user.nickname)}.rss' %></link>
    </image>

    <%= render Phoenix.Controller.view_module(@conn), "_author.rss", assigns %>

    <%= if last_activity(@activities) do %>
      <link rel="next"><%= '#{Routes.user_feed_url(@conn, :feed, @user.nickname)}.rss?max_id=#{last_activity(@activities).id}' %></link>
    <% end %>

    <%= for activity <- @activities do %>
    <%= render Phoenix.Controller.view_module(@conn), "_activity.rss", Map.merge(assigns, prepare_activity(activity)) %>
    <% end %>
  </channel>
</rss>